### ISSUE TITLE
Missing ts folder

### ISSUE THREAD

**Issue by pier-oliviert** [toji/webgl-source#1]
I just wanted to run it on my local server and the ts/ folder is missing from this repo. I didn't watch your full video so maybe it is because it's too big to fit on github?

Thank you!

**Comment by pier-oliviert** [comment]
nevermind, I read the property stuff, gotta copy it from the game (Which I have deleted 2 months ago :( )

Thank you anyway!

**Comment by toji** [comment]
Yeah, just as a clarification: I will not be redistributing any Valve resources. To run this demo you will need to extract those files from the game GCF files yourself. There are a lot of community resources out there that describe how to do that.

**Comment by pier-oliviert** [comment]
Maybe writing it explicitly on your readme would make it easier for those of us who just wants to try it out very quickly.

Thank you

**Comment by toji** [comment]
Good point, I'll update that soon.

**Comment by toji** [comment]
And... done.
